### ISSUE TITLE
Zooming is very hit or miss, and zooming causes scene rotation even with rotation disabled

### ISSUE THREAD

**Issue by douglasg14b** [RolandCsibrei/babylonjs-hammejs-arc-rotate-camera#2]
Zooming is very hit or miss, sometimes it works, most of the time it does not. When it does, zooming in and out rotates the camera even when`disableRotation = true`

**Comment by RolandCsibrei** [comment]
Hey! Thanks for reporting the issues. There is a huge update coming with
many issues solved today. Stay tuned.

**Comment by douglasg14b** [comment]
Sure thing!

**Comment by RolandCsibrei** [comment]
Updated.

**Comment by RolandCsibrei** [comment]
Fixed
